In [1]:
import pandas as pd
import numpy as np

### TODO:
* https://github.com/JosPolfliet/pandas-profiling/issues/25

In [7]:
df = pd.read_csv('train.txt',  sep=';', low_memory=False)
df.columns

Index(['customernumber', 'date', 'salutation', 'title', 'domain',
       'datecreated', 'newsletter', 'model', 'paymenttype', 'deliverytype',
       'invoicepostcode', 'delivpostcode', 'voucher', 'advertisingdatacode',
       'case', 'numberitems', 'gift', 'entry', 'points', 'shippingcosts',
       'deliverydatepromised', 'deliverydatereal', 'weight', 'remi', 'cancel',
       'used', 'w0', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'w9',
       'w10', 'target90'],
      dtype='object')

In [11]:
df.head()

,customernumber,date,salutation,title,domain,datecreated,newsletter,model,paymenttype,deliverytype,...,w2,w3,w4,w5,w6,w7,w8,w9,w10,target90
0,41191,2008-12-01,0,0,9,2008-12-01,0,2,2,0,...,0,0,0,0,0,0,0,0,0,0
1,38860,2008-12-16,1,0,4,2008-12-16,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,61917,2008-08-19,0,0,12,2008-08-19,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,40647,2008-06-16,1,0,8,2008-06-16,0,1,0,0,...,0,0,0,2,0,0,0,0,0,0
4,1347,2008-08-08,0,0,1,2008-08-08,0,1,1,1,...,2,0,0,0,0,0,0,0,0,0

In [10]:
import pandas_profiling
pandas_profiling.ProfileReport(df).to_file(outputfile="myoutputfile.html")